from __future__ import annotations

# 24 Challenging Directional Lateral Prompts (100% Directional, 12 Left_Of + 12 Right_Of)
# Designed to eliminate ceiling effects via same-class attribute pairs, visual clutter, and counter-canonical priors.

LATERAL_HARD_24_SPECS = [
    # --- 12 Left_Of Prompts ---
    {
        "id": "hard_lat_01",
        "prompt": "a blue ceramic mug to the left of a red ceramic mug on a wooden kitchen table",
        "subject": "blue ceramic mug",
        "object": "red ceramic mug",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_02",
        "prompt": "a fresh green apple to the left of a bright red apple on a white porcelain plate",
        "subject": "green apple",
        "object": "red apple",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_03",
        "prompt": "a lit gold candle to the left of a lit silver candle on a stone mantelpiece",
        "subject": "gold candle",
        "object": "silver candle",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_04",
        "prompt": "a purple hardcover book to the left of an orange hardcover book on a crowded office desk",
        "subject": "purple hardcover book",
        "object": "orange hardcover book",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_05",
        "prompt": "a yellow sports car to the left of a black sports car on a wet asphalt street",
        "subject": "yellow sports car",
        "object": "black sports car",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_06",
        "prompt": "a tall blue glass bottle to the left of a clear glass bottle on a reflective marble bar",
        "subject": "blue glass bottle",
        "object": "clear glass bottle",
        "relation": "left_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_07",
        "prompt": "a silver fork to the left of a metal spoon beside a dinner plate on a linen tablecloth",
        "subject": "silver fork",
        "object": "metal spoon",
        "relation": "left_of",
        "category": "cluttered_scene",
    },
    {
        "id": "hard_lat_08",
        "prompt": "a wooden acoustic guitar to the left of a black microphone stand on a concert stage",
        "subject": "acoustic guitar",
        "object": "microphone stand",
        "relation": "left_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_09",
        "prompt": "a white coffee cup to the left of a pair of eyeglasses next to an open notebook on a desk",
        "subject": "white coffee cup",
        "object": "eyeglasses",
        "relation": "left_of",
        "category": "cluttered_scene",
    },
    {
        "id": "hard_lat_10",
        "prompt": "a potted green fern to the left of a bronze desk clock in a sunlit library",
        "subject": "potted green fern",
        "object": "bronze desk clock",
        "relation": "left_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_11",
        "prompt": "a slice of chocolate cake to the left of a glass of milk on a wooden cafe table",
        "subject": "chocolate cake",
        "object": "glass of milk",
        "relation": "left_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_12",
        "prompt": "a vintage brass compass to the left of a rolled parchment map on a wooden captains desk",
        "subject": "brass compass",
        "object": "parchment map",
        "relation": "left_of",
        "category": "complex_scene",
    },

    # --- 12 Right_Of Prompts ---
    {
        "id": "hard_lat_13",
        "prompt": "a red ceramic mug to the right of a blue ceramic mug on a wooden kitchen table",
        "subject": "red ceramic mug",
        "object": "blue ceramic mug",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_14",
        "prompt": "a bright red apple to the right of a fresh green apple on a white porcelain plate",
        "subject": "red apple",
        "object": "green apple",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_15",
        "prompt": "a lit silver candle to the right of a lit gold candle on a stone mantelpiece",
        "subject": "silver candle",
        "object": "gold candle",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_16",
        "prompt": "an orange hardcover book to the right of a purple hardcover book on a crowded office desk",
        "subject": "orange hardcover book",
        "object": "purple hardcover book",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_17",
        "prompt": "a black sports car to the right of a yellow sports car on a wet asphalt street",
        "subject": "black sports car",
        "object": "yellow sports car",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_18",
        "prompt": "a clear glass bottle to the right of a tall blue glass bottle on a reflective marble bar",
        "subject": "clear glass bottle",
        "object": "blue glass bottle",
        "relation": "right_of",
        "category": "same_class_color",
    },
    {
        "id": "hard_lat_19",
        "prompt": "a metal spoon to the right of a silver fork beside a dinner plate on a linen tablecloth",
        "subject": "metal spoon",
        "object": "silver fork",
        "relation": "right_of",
        "category": "cluttered_scene",
    },
    {
        "id": "hard_lat_20",
        "prompt": "a black microphone stand to the right of a wooden acoustic guitar on a concert stage",
        "subject": "microphone stand",
        "object": "acoustic guitar",
        "relation": "right_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_21",
        "prompt": "a pair of eyeglasses to the right of a white coffee cup next to an open notebook on a desk",
        "subject": "eyeglasses",
        "object": "white coffee cup",
        "relation": "right_of",
        "category": "cluttered_scene",
    },
    {
        "id": "hard_lat_22",
        "prompt": "a bronze desk clock to the right of a potted green fern in a sunlit library",
        "subject": "bronze desk clock",
        "object": "potted green fern",
        "relation": "right_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_23",
        "prompt": "a glass of milk to the right of a slice of chocolate cake on a wooden cafe table",
        "subject": "glass of milk",
        "object": "chocolate cake",
        "relation": "right_of",
        "category": "complex_scene",
    },
    {
        "id": "hard_lat_24",
        "prompt": "a rolled parchment map to the right of a vintage brass compass on a wooden captains desk",
        "subject": "parchment map",
        "object": "brass compass",
        "relation": "right_of",
        "category": "complex_scene",
    },
]
